apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lpze7buze-go
  janus-idp.io/tekton: lpze7buze-go
  backstage.io/kubernetes-id: lpze7buze-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lpze7buze-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
