apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lpze7buze-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lpze7buze-go 
  name: lpze7buze-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lpze7buze-go 
